# .streamlit/secrets.toml

# --- SMTP Configuration ---
[smtp]
host = "smtp.gmail.com"
port = 587
user = "safepost2000@gmail.com"
password = "nink vpsh fwyc inlh"
from_email = "safepost2000@gmail.com" # Renamed 'from' to 'from_email'
enable_tls = true # Standard for port 587, explicitly set for clarity

# --- Google Sheets Service Account Key ---
[google_sheets]
# The entire JSON service account key as a multi-line string.
# Ensure correct indentation and escape newlines in the private_key if not using triple quotes.
# Using triple quotes ("""...""") allows direct paste of the JSON.
service_account_key = """
{
  "type": "service_account",
  "project_id": "attended-462110",
  "private_key_id": "ad5d136369f3cc4630bc8b7a9beeebfc2e673490",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRhu7mg6mcPvDh\nabcZhIVgQ+jUkg5bLMsiuMU7K6zuhmlAVbZeH0Xa4aLfpG9i36WtY3Ky3Qir1eLa\nwpmlN2L91CdX9nYUt5pnMH5jAxPgbpN980/wLB1ufq5HOO9Irm1ZeAWuWXpDpa7g\nhWV5vg+5jNr+DuWJHXubZAII2AhJexHZ14fSofwskl92qFAAquIWUc5Ue5tRldv0\nTfQPcxINSKgU1t755tUEO/TS/k+XisjSf8jSSvcnoEFJAOwBwEX9O7yDOabEMk1V\nsFEtlu9W2c85SwToTv5L+Bb7KJ0kmkXYcuQzGgXNR12H24KGKSGmgDF82EH1XIfk\nrbNm/tjrAgMBAAECggEAJVPA72uSE7upOYhOKMNvGpQQooWcHRLOP+e430aCouPj\nF1dk4ZuP5Wa+yjJ5R5kp++FoSCydzsWb3JTRqCkewRCrzsou232EozczE950OLrk\nJghE1svZ+L+RoD8gUTo8XhiFDIVy8OsMghZ1QtbXXbadbVEQ2yyuydrLEs2mwoHl\nmihEGGaTi6pry8uScR0M1gIwNRQ6q1jmUo5LaklDuKyPd9XVu1SgrvM+9XjmC9X7\nYklFH4rxeFOCh2mrsaST+XWZ2XiNQdRFxDWY2A+2S3foXrmiAk5YC045yJrNaAYs\n8jV1HfrVdXtflk3B9czt4MaJsYxqXzfeI0tRdSioIQKBgQDLPPlX7Jg6J6YVW2vE\n0LGdnQXwsNTSP9BfgoV3A2Rg7kIwJPnveyJjINw30JK75Tv6e6PaCYzhgsVM4Vvg\nMWYbfuyGtCc44StywrckkcYbtKTFuXljM032NlLYtP79nPM/JFxpuEyrtOXduXV4\nt7SAkYYAJHEs+jh0A/4GgciF8wKBgQC3TogjpPBjG7TFyxScDPwxNUxhWeAcgCCm\n8Rak8DVX0bAeI/xFUs+XodRNfdak9H4mVBuhKiV5Z73S4w7HmSh22ec8pUcE7Cvd\n02bePsnQ39nouH8Eqo0xud8JO+OpLCmtLm6DMwNkoQDHU6HSzlH5DKAfAh0CWKS+\nB3e2ZBlHKQKBgB+VvUZtzYaULNp617fBmyjcg1TRlnGKW07MkQNa8pmhzYV/6a+z\nmjd/ntnJv1QWHwkhd+hlvZA6a4E0MLwZ0T2KryWMD+BmFgOCwUWcpgYeP9E+hxbk\nnUQbUyq8jjhJ0P/KHdaMPtYcifC4Zso4+oNUmlehUjlkNavKBwtp1gkDAoGABpCG\naZhfj30PhUHXlBsW8QAyow3f68Ve/fueTvvXPTTiNMIfJ7BmhMyj2L6X8EJdPiwm\n7SegPe/MKYA+KEHA5Di7gj19BJ0cmQ4YEf93pMZPfHkW+2jMM6qvZRpC9e0B9RTD\nmmk6RuFJMNo64lzHLL8aAOJHfa0FAVUtIVgGW7kCgYAGCEO28pGu6cRlwGqZMjc9\nBSXc7+BOkRkc2/YVenpEciL5fuedD0eAgf+wpTTjPEx2iBuLUHewg4gpVb6yhZY4\njsy3wzDwNdozQpZM83Vuz8Y7uD5f+sosw4SyuH/BsZ8ibmORJDdCyWTYx7M5ZJJN\nqOAKCPALR07vy/OP/8mlUA==\n-----END PRIVATE KEY-----\n",
  "client_email": "zeal-605@attended-462110.iam.gserviceaccount.com",
  "client_id": "109329796716855981353",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/zeal-605%40attended-462110.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
spreadsheet_id = "11IEx5m5zLjn3OfXN5Man7gZ04YicktFj5kgh15EjKtQ" # <<< IMPORTANT: REPLACE WITH YOUR ACTUAL SPREADSHEET ID
